const commonCards = [
  `Ändring i föredragningslistan`,
  `Det sker en sakupplysning`,
  `"Det var bättre förr"`,
  `Diskussion på samma punkt över en timme`,
  `Diskussion som "fråga"`,
  `Fler än 5 personer vinner Betting`,
  `Ingen revisor är på plats`,
  `Ingen säger något på diskussion, bara tummar upp`,
  `"Kan du upprepa frågan?"`,
  `"Kan vi hålla frågorna/diskussionen relevanta"`,
  `Någon anser betting vara riggat`,
  `Någon (Douglas) berättar sektionshistoria`,
  `Någon drar över talartiden och vägrar sluta prata`,
  `Någon hoppar/klättrar över en bänkrad`,
  `Någon i styrelsen tar av sig hatten`,
  `Någon klagar på betting inte öppnats`,
  `Någon visar brain-rott på stora skärmen`,
  `Någon öppnar dörren när den ska vara stängd`,
  `Någon säger något halv-kul (minst 20% behöver skratta)`,
  `Någon säger något jättekul (minst 80% behöver skratta)`,
  `Någons telefon låter`,
  `Någon tar mer än 10 sekunder på sig för att få mikrofonen att funka`,
  `Något kallas odemokratiskt`,
  `Ordvits ingen skrattar åt`,
  `"På min tid"`,
  `Rösträknarna glömmer att meddela resultat av sluten omröstning`,
  `Rummet är en kvav öken`,
  `Sekreterare frågar om någons namn`,
  `Skämt om medias ekonomi`,
  `"Sluta stäng av mikrofonen"`,
  `Sträck i debatten`,
  `Talarlistan används`,
  `Talman avbryter någon mitt i meningen`,
  `Talman talar fel`,
  `Talman tappar förmågan att tala`,
  `Teknikstrul följt av livlig diskussion om lösning`,
  `"Tjing"`,
  `Valkandidater har gått iväg`,
  `Elektroniskt röstningssystem strular`,
  `Wikipediasidan för Schulze visas på skärmen`,
  `"De här borde lösas bättre till nästa år"`,
  `Talman börjar argumentera för en ståndpunkt i sakfråga`,
  `Talman citerar mötesordningen fel`,
  `Talman glömmer vilken punkt mötet är på`,
  `Talman mumlar`,
  `Talman suckar högljutt åt någons förslag`,
  `Ordningsfråga`,
  `Någon däremot? "Nej"`,
];

export default commonCards;
