export default [
  `Ändring i föredragningslistan`,
  `SM vill bryta mot stadgarna`,
  `Beslutsträd`,
  `Det är fler än 2 ändringsyrkande på samma motion/proposition`,
  `Det saknas kandidater, vakantställning`,
  `Det sker en sakupplysning`,
  `"Det var bättre förr"`,
  `"Ju förr desto bättre"`,
  `Diskussion på samma punkt över en timme`,
  `Diskussion som "fråga"`,
  `En motion/propp ingen förstår`,
  `En motion/propp är klar på under 3 minuter`,
  `En motion/propp tar mer än 45 minuter`,
  `Fler än 5 personer vinner Betting`,
  `"Hej SM!"`,
  `Ingen revisor är på plats`,
  `Ingen säger något på diskussion, bara tummar upp`,
  `Ingen vet vilket ändringsyrkande som gäller`,
  `Justerarna lämnar innan mötets slut`,
  `Kandidat/motionär presenterar i max 20 sekunder`,
  `"Kan du upprepa frågan?"`,
  `"Kan vi hålla frågorna/diskussionen relevanta"`,
  `Talman börjar argumentera för en ståndpunkt i sakfråga`,
  `Talman citerar mötesordningen fel`,
  `Talman glömmer vilken punkt mötet är på`,
  `Talman läser upp fel att-sats`,
  `Talman mumlar`,
  `Talman suckar högljutt åt någons förslag`,
  `Motion avslås`,
  `Motionssvar saknas`,
  `Någon anser betting vara riggat`,
  `Någon (Douglas) berättar sektionshistoria`,
  `Någon drar över talartiden och vägrar sluta prata`,
  `Någon hoppar/klättrar över en bänkrad`,
  `Någon i styrelsen tar av sig hatten`,
  `Någon jämkar sig`,
  `Någon klagar på betting inte öppnats`,
  `Någon visar brain-rott på stora skärmen`,
  `Någon öppnar dörren när den ska vara stängd`,
  `Någon säger något halv-kul (minst 20% behöver skratta)`,
  `Någon säger något jättekul (minst 80% behöver skratta)`,
  `Någons telefon låter`,
  `Någon tar mer än 10 sekunder på sig för att få mikrofonen att funka`,
  `Något kallas odemokratiskt`,
  `Ordningsfråga`,
  `Ordvits ingen skrattar åt`,
  `"På min tid"`,
  `Personval i rösträknar och/eller justerarval`,
  `Rösträknarna glömmer att meddela resultat av sluten omröstning`,
  `Rummet är en kvav öken`,
  `Sekreterare frågar om någons namn`,
  `Skämt om medias ekonomi`,
  `"Sluta stäng av mikrofonen"`,
  `SM börjar minst 15 min sent`,
  `"SMingo!"`,
  `SM tar mer än 2 timmar`,
  `SM tar mer än 4 timmar`,
  `Sträck i debatten`,
  `Styrelsen har smugit in en oseriös att-sats`,
  `Talarlistan används`,
  `Talman avbryter någon mitt i meningen`,
  `Talman talar fel`,
  `Talman tappar förmågan att tala`,
  `Teknikstrul följt av livlig diskussion om lösning`,
  `"Tjing"`,
  `Valkandidat dyker inte upp på SM`,
  `Valkandidater har gått iväg`,
  `"Vi behöver inte prata om motionen då alla läst handlingarna"`,
  `"Någon vill lyfta originalmotionen eller någon alternativ kombination av ändringsyrkanden"`,
  `Elektroniskt röstningssystem strular`,
  `Wikipediasidan för Schulze visas på skärmen`,
  `Mer än en kandidat i ett val`,
  `"De här borde lösas bättre till nästa år"`,
];
