export default [
    `Ändring i föredragningslistan`,
    `Det saknas kandidater, vakantställning`,
    `Det sker en sakupplysning`,
    `"Det var bättre förr"`,
    `"De här borde lösas bättre till nästa år"`,
    `Diskussion på samma punkt över en timme`,
    `Diskussion som "fråga"`,
    `Et val är klart på under 5 minuter`,
    `En val tar mer än 30 minuter`,
    `Fler än 5 personer vinner Betting`,
    `Folk blir påminda att fokusera på valkandidaternas positiva sidor`,
    `"Hej VM!"`,
    `Ingen revisor är på plats`,
    `Ingen säger något på diskussion, bara tummar upp`,
    `Kandidat presenterar i max 20 sekunder`,
    `"Kan du upprepa frågan?"`,
    `"Kan vi hålla frågorna/diskussionen relevanta"`,
    `Mötesordförande citerar mötesordningen fel`,
    `Mötesordförande glömmer vilken punkt mötet är på`,
    `Mötesordförande läser upp fel sak`,
    `Mötesordförande mumlar i rask takt`,
    `Mötesordförande suckar högljutt åt någons förslag`,
    `Någon anser betting vara riggat`,
    `Någon däremot? "Nej"`,
    `Någon (Douglas) berättar sektionshistoria`,
    `Någon drar över talartiden och vägrar sluta prata`,
    `Någon hoppar/klättrar över en bänkrad`,
    `Någon i styrelsen tar av sig hatten`,
    `Någon kallas rättshaverist`,
    `Någon klagar på betting inte öppnats`,
    `Någon visar brain-rott på stora skärmen`,
    `Någon öppnar dörren när den ska vara stängd`,
    `Någon säger något halv-kul (minst 20% behöver skratta)`,
    `Någon säger något jättekul (minst 80% behöver skratta)`,
    `Någons telefon låter`,
    `Någon tar mer än 10 sekunder på sig för att få mikrofonen att funka`,
    `Något kallas odemokratiskt`,
    `Ordningsfråga i ordningsfråga`,
    `Ordningsfråga om beslutsordningen`,
    `Ordvits ingen skrattar åt`,
    `"På min tid"`,
    `Rösträknarna glömmer att meddela resultat av sluten omröstning`,
    `Rummet är en kvav öken`,
    `Sekreterare frågar om någons namn`,
    `Skämt om medias ekonomi`,
    `"Sluta stäng av mikrofonen"`,
    `VM börjar minst 15 min sent`,
    `"VMingo!"`,
    `VM tar mer än 3 timmar`,
    `Sträck i debatten`,
    `Talarlistan används`,
    `Talman avbryter någon mitt i meningen`,
    `Talman talar fel`,
    `Talman tappar förmågan att tala`,
    `Teknikstrul följt av livlig diskussion om lösning`,
    `"Tjing"`,
    `Valkandidat dyker inte upp på VM`,
    `Valkandidater har gått iväg`,
    `"Ni har ju alla läst valhandlingarna men ..."`,
    `Elektroniskt röstningssystem strular`,
    `Wikipediasidan för Schulze visas på skärmen`,
  ];
